### ISSUE TITLE
Slack Channel?

### ISSUE THREAD

**Issue by MasterSwift** [PureSwift/Cacao#25]

**Comment by ardawan** [comment]
I follow the README file and installed the dependencies and download the repository on my computer.
I tried to run the CacaoDemo/Sources/Main.swift but I got an Error!
How to fix this?

by the way, I'm running Debian 9, not Ubuntu.

Thank you in advance

![image](https://user-images.githubusercontent.com/6112301/28805299-9f702bce-769b-11e7-9805-124714a53ba0.png)
![image](https://user-images.githubusercontent.com/6112301/28805420-7946035a-769c-11e7-9988-bc1ff32ab4f6.png)

**Comment by MFAshby** [comment]
It's likely because not everything was built. Please try running 'swift build' in the root of the project. 

This should compile all the targets in the Project.swift file ( i.e. the cacao library, and the demo project ) 

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ardawan** [comment]
Thanks for the reply but I did run "swift build" in the root folder(Cacao-master) and I got another error.

![image](https://user-images.githubusercontent.com/6112301/28902386-340b3bca-7831-11e7-8f90-f75ba6b2c049.png)

**Comment by MFAshby** [comment]
Great, this looks like a build error. The line which says the error is in CGRect.swift, in the Silica folder tells me this is a problem building the Silica project, which Cacao depends on. 

Try downloading and building Silica on it's own, and if there's still an error file a bug with that project so the owner can fix it. 

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MFAshby** [comment]
https://github.com/PureSwift/Silica
This is the Silica repo. 

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
