### ISSUE TITLE
The performance might not be as well as UIKit in iOS devices theoretically.

### ISSUE THREAD

**Issue by lilidan** [PureSwift/Cacao#38]
I found that Cacao is using Cairo for 2D rendering.It's said that Cairo's performance is worse than Skia (which is based on OpenGL and Vulkan). And Metal2.0 is even much faster than Vulkan. 

Take Flutter For example, it performs not so well in iOS. The render engine should be taken into consideration.

**Comment by lilidan** [comment]
I'm not very sure, maybe we should get some benchmarks in devices.

**Comment by colemancda** [comment]
This should never be used in iOS. Cairo is used for CoreGraphics, which uses the CPU on iOS and Mac, so it should not be very different from native. You are always welcome to use any other framework and draw to the SDL buffer directly.
