### ISSUE TITLE
miss Cairo.framework Silica,framework

### ISSUE THREAD

**Issue by joywt** [PureSwift/Cacao#4]
miss Cairo.framework Silica,framework and Typealias.swift

**Comment by colemancda** [comment]
run `carthage bootstrap`

**Comment by joywt** [comment]
** BUILD FAILED **
The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by colemancda** [comment]
You have to install the latest [Swift 3.0 Development snapshot](https://swift.org/builds/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a/swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a-osx.pkg).

The run this command before running `carthage`: 
`export PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:"${PATH}"`
`export TOOLCHAINS=swift`

**Comment by joywt** [comment]
![73b72787-49b4-417d-b4cc-2bf39ce4599d](https://cloud.githubusercontent.com/assets/6982586/15665115/82f8634a-273b-11e6-96d8-107d23e03c3d.png)
It's not work .
![7ef20578-8d61-4c8a-b27d-ea3508c069e3](https://cloud.githubusercontent.com/assets/6982586/15665138/aad55cc4-273b-11e6-8d76-3ed5959121a2.png)

**Comment by colemancda** [comment]
You are only changing the Xcode toolchain, you have to change the toolchain in the current Terminal session. Run:

```
export PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:"${PATH}"
export TOOLCHAINS=swift
carthage bootstrap
```

**Comment by joywt** [comment]
Thanks，it's work
