### ISSUE TITLE
Mainfest parse errors, Ubuntu 18.10, Swift 5.0.0

### ISSUE THREAD

**Issue by rajamohan0s** [PureSwift/Cacao#41]
![Screenshot 2019-04-08 at 2 04 39 PM](https://user-images.githubusercontent.com/20209643/55710032-4fb45500-5a07-11e9-81b2-b8732e7bba8c.png)

How can I fix it? Thanks!

**Comment by yoahnl** [comment]
same problem here.

**Comment by rajamohan0s** [comment]
To fix this issue, **We have to update all related sources to Swift 5.0.** Highly appreciated Cacao author's work. Thanks!
